services:
  db:
    image: postgres:16
    container_name: lab_db
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  app:
    build: .
    container_name: lab_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: lab_db
      DB_USER: lab_user
      DB_PASSWORD: lab_pass
      APP_CONTEXT: lab
      ADMIN_USER: admin
      ADMIN_PASS: admin123
    ports:
      - "8080:8080"
      - "8081:4848"

      